# generated by datamodel-codegen:
#   filename:  protocol.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Dict, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Approve1(Enum):
    never = 'never'
    always = 'always'


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    mime: str
    size: Annotated[int, Field(ge=0)]
    uri: str


class AttachmentTool(Enum):
    read = 'read'
    view = 'view'


class AudioData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    format: str


class ClientInput4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    args: Any | None = None
    name: str
    turn_id: str | None = None
    type: Literal['client.action']


class ClientInput5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str
    payload: Any | None = None
    type: Literal['interrupt.resume']


class ClientInput7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    error: str
    id: str
    retryable: bool
    type: Literal['tool.error']


class ClientPayload4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: Any | None = None
    name: str
    type: Literal['client.action']


class ContentPart1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    type: Literal['text']


class ContentPart4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_audio: AudioData
    type: Literal['input_audio']


class DecisionAction4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    id: str | None = None
    response: Annotated[
        Any,
        Field(
            description="An `LlmResponse`, or the provider's own response when the\n`llm.execute` this answers carried a `format`."
        ),
    ]
    type: Literal['llm.result']


class DecisionAction9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str | None = None
    payload: Any | None = None
    reason: str
    type: Literal['interrupt']


class DecisionAction10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str
    payload: Any | None = None
    type: Literal['interrupt.resolve']


class DecisionAction11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Annotated[
        str,
        Field(
            description='Where a connection is declared: `mcp.<id>` or `plugin.<id>.mcp.<server>`'
        ),
    ]
    type: Literal['connector.sync']


class DecisionAction12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: Any | None = None
    type: Literal['done']


class DecisionTrigger1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.start']


class DecisionTrigger3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: Any | None = None
    name: str
    type: Literal['client.action']


class DecisionTrigger9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str
    payload: Any | None = None
    type: Literal['interrupt.resumed']


class DeferToolsStrategy(Enum):
    search = 'search'


class Disposition(Enum):
    inline = 'inline'
    attachment = 'attachment'


class EffectKind1(Enum):
    tool_call = 'tool_call'
    subagent = 'subagent'
    llm_call = 'llm_call'


class EffectStatus1(Enum):
    pending = 'pending'
    completed = 'completed'
    failed = 'failed'
    retry_scheduled = 'retry_scheduled'
    queued = 'queued'


class ErrorCode(Enum):
    provider_error = 'provider_error'
    rate_limited = 'rate_limited'
    refused = 'refused'
    budget_exceeded = 'budget_exceeded'
    deadline_exceeded = 'deadline_exceeded'
    invalid_response = 'invalid_response'
    handler_error = 'handler_error'
    worker_unreachable = 'worker_unreachable'
    unroutable = 'unroutable'
    internal = 'internal'


class ErrorInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: ErrorCode
    detail: Annotated[
        Any | None,
        Field(
            description='Small structured details, such as a status or the llm blocks that\nexist.'
        ),
    ] = None
    message: Annotated[
        str,
        Field(
            description='One sentence the engine wrote, safe to show a human. Never a raw\ndocument. An unbounded body belongs in the log.'
        ),
    ]
    param: Annotated[
        str | None,
        Field(
            description='The one input to fix, when the failure names one. For example\n`agent.llm` or `actions[0].type`.'
        ),
    ] = None


class FileData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_data: str
    filename: str


class Handler(Enum):
    server = 'server'
    worker = 'worker'
    client = 'client'


class ImageUrl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class InterruptOption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    style: Annotated[
        str | None,
        Field(description='`primary` or `danger`. Anything else shows plain.'),
    ] = None
    value: Annotated[
        Any,
        Field(
            description="Delivered unchanged as the resolution's `payload`. The worker chooses\nwhat it means."
        ),
    ]


class InterruptOrigin(Enum):
    system = 'system'
    operator = 'operator'
    machine = 'machine'
    frontend = 'frontend'


class InterruptPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expiresAt: Annotated[str | None, Field(description='RFC 3339. Display only.')] = (
        None
    )
    message: Annotated[
        str | None,
        Field(
            description="Markdown. A channel converts it as it needs. Without it, a channel\nshows the interrupt's `reason`."
        ),
    ] = None
    metadata: Annotated[
        Any | None,
        Field(
            description='Free-form, delivered to clients unchanged. `metadata.options` is a\nlist of [`InterruptOption`], which Slack shows as buttons.'
        ),
    ] = None
    responseSchema: Annotated[
        Any | None,
        Field(description='JSON Schema for the expected resolution payload.'),
    ] = None
    toolCallId: Annotated[
        str | None, Field(description='Binds the interrupt to a prior tool call.')
    ] = None


class InterruptResponder(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    channel: Annotated[
        str, Field(description='The channel kind, e.g. `slack`, `ag-ui`.')
    ]
    label: Annotated[
        str | None,
        Field(description="The chosen option's label, when the resolution was a pick."),
    ] = None
    style: Annotated[
        str | None,
        Field(
            description="The chosen option's `style`, when the resolution was a pick."
        ),
    ] = None
    user: Annotated[str | None, Field(description='Channel-native user id.')] = None


class LlmFormat(Enum):
    openai = 'openai'
    anthropic = 'anthropic'


class LlmTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    defer: Annotated[
        bool | None,
        Field(
            description="Keep this definition out of the request.\n\nThe engine still records it, still routes a call to it, and still finds\nit in a search. Only the request leaves it out. That keeps a large tool\nset out of the model's context and out of the cached prefix.\n\nAny source can set it. Deferral belongs to a tool, not to where the tool\ncame from."
        ),
    ] = None
    description: str
    input: Annotated[
        Any | None,
        Field(
            description='JSON Schema for the arguments. Absent declares a tool with no\narguments. The engine checks every call against it.'
        ),
    ] = None
    name: str
    output: Annotated[
        Any | None,
        Field(
            description='JSON Schema the result must satisfy. The model never sees it. A result\nthat breaks it becomes a terminal tool error.'
        ),
    ] = None


class McpAnnounce(Enum):
    auto = 'auto'
    never = 'never'


class McpAuthFailure(Enum):
    interrupt = 'interrupt'
    degrade = 'degrade'


class McpToolSyncFailure(Enum):
    warn = 'warn'
    silent = 'silent'


class McpTools(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    defer: Annotated[
        bool | None,
        Field(
            description="Keep every surviving tool out of the request. See [`LlmTool::defer`].\nAbsent ⇒ the agent's `defer_tools`."
        ),
    ] = None
    exclude: list[str] | None = None
    idempotent: bool | None = None
    include: list[str] | None = None
    non_destructive: bool | None = None
    read_only: bool | None = None


class ReasoningEffort(Enum):
    xhigh = 'xhigh'
    high = 'high'
    medium = 'medium'
    low = 'low'
    minimal = 'minimal'
    none = 'none'


class ReasoningProvider(Enum):
    anthropic = 'anthropic'
    openai = 'openai'
    openrouter = 'openrouter'


class ResourceContents(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blob: str | None = None
    mimeType: str | None = None
    text: str | None = None
    uri: str


class ResponseImage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class ResumeStatus(Enum):
    resolved = 'resolved'
    cancelled = 'cancelled'


class RetryOverride(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backoff_base_secs: Annotated[int | None, Field(ge=0)] = None
    backoff_max_secs: Annotated[int | None, Field(ge=0)] = None
    max_attempts: Annotated[int | None, Field(ge=0)] = None
    queue_timeout_secs: Annotated[int | None, Field(ge=0)] = None
    run_timeout_secs: Annotated[int | None, Field(ge=0)] = None
    total_timeout_secs: Annotated[int | None, Field(ge=0)] = None


class RetryPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backoff_base_secs: Annotated[int, Field(ge=0)]
    backoff_max_secs: Annotated[int, Field(ge=0)]
    max_attempts: Annotated[
        int, Field(description='Total attempts, not retries. `1` gives one try.', ge=0)
    ]
    queue_timeout_secs: Annotated[int | None, Field(ge=0)] = None
    run_timeout_secs: Annotated[int | None, Field(ge=0)] = None
    total_timeout_secs: Annotated[int | None, Field(ge=0)] = None


class Role(Enum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class SkillMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    name: str


class SpawnMode(Enum):
    blocking = 'blocking'
    detached = 'detached'
    wait = 'wait'


class StoredContent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    type: Literal['text']


class StoredContent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['blob']
    uri: str


class StoredContent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mimeType: str | None = None
    name: str | None = None
    type: Literal['link']
    uri: str


class StoredContent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    mime: str
    size: Annotated[int, Field(ge=0)]
    uri: str
    type: Literal['attachment']


class StoredResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: (
        list[StoredContent1 | StoredContent2 | StoredContent3 | StoredContent4] | None
    ) = None
    isError: bool | None = None
    structuredContent: Any | None = None


class SubagentMode(Enum):
    blocking = 'blocking'
    detached = 'detached'
    any = 'any'


class SubagentToolsStrategy(Enum):
    per_agent = 'per_agent'
    single = 'single'


class Subject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    issuer: Annotated[
        str,
        Field(
            description="Where a person's name comes from: `slack`, `app`, `cli`, or another source\na deployment registers. Set by whatever authenticated the request, never\nread from the request.",
            title='Issuer',
        ),
    ]


class ToolCallChunk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str | None = None
    id: str
    name: str | None = None


class ToolCallFunction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str
    name: str


class ToolContent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    type: Literal['text']


class ToolContent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    mimeType: str
    type: Literal['image']


class ToolContent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    mimeType: str
    type: Literal['audio']


class ToolContent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resource: ResourceContents
    type: Literal['resource']


class ToolContent5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mimeType: str | None = None
    name: str | None = None
    type: Literal['resource_link']
    uri: str


class ToolInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['valid']
    value: Any


class ToolInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str
    status: Literal['invalid']
    value: Any


class ToolInput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str
    status: Literal['malformed']


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache_read: Annotated[
        int,
        Field(
            description='The part of `input` the provider read from the cache.', ge=0
        ),
    ]
    cache_write: Annotated[
        int,
        Field(description='The part of `input` the provider wrote to the cache.', ge=0),
    ]
    input: Annotated[
        int, Field(description='Every input token of the call, cached or not.', ge=0)
    ]
    output: Annotated[int, Field(ge=0)]
    provider: Annotated[
        Any | None,
        Field(
            description='The counts as the provider reported them, for a number this type does\nnot name.'
        ),
    ] = None
    total: Annotated[int, Field(description='`input` and `output` together.', ge=0)]
    uncached_input: Annotated[
        int, Field(description='The part of `input` the provider read fresh.', ge=0)
    ]


class VideoUrl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class Visibility(Enum):
    shared = 'shared'
    private = 'private'


class Wire1(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='A size on the wire: bytes, or a word a person writes.',
            ge=0,
            title='Size',
        ),
    ]


class WorkerIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: dict[str, str]
    subject: Subject | None = None
    visibility: Visibility | None = None


class WorkerRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    url: str | None = None


class AgentPlugin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approve: Annotated[
        Approve1 | Literal['destructive'] | None,
        Field(
            description="Which of a connection's calls stop for a person.",
            title='Approve',
        ),
    ] = None
    auth_failure: McpAuthFailure | None = None
    description: str | None = None
    id: str
    servers: Annotated[
        list[str] | None,
        Field(description="The plugin's server names, from its bundle."),
    ] = None
    skills: list[SkillMeta] | None = None
    tool_sync_failure: McpToolSyncFailure | None = None
    tools: Annotated[
        McpTools | None, Field(description="Applied to each of the plugin's servers.")
    ] = None


class AgentTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    defer: Annotated[
        bool | None,
        Field(
            description="Keep this tool out of the request. See [`LlmTool::defer`]. Absent ⇒\nthe agent's `defer_tools`."
        ),
    ] = None
    description: str | None = None
    handler: Handler | None = None
    input: Any | None = None
    name: str
    output: Any | None = None


class Attachments(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    max_inline: Wire1 | str | None = None
    rules: dict[str, Disposition] | None = None
    tools: list[AttachmentTool] | None = None


class ClientContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context: list[Any] | None = None
    forwarded_props: Any | None = None
    state: Any | None = None
    tools: list[AgentTool] | None = None


class ClientInput6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    content: (
        list[ToolContent1 | ToolContent2 | ToolContent3 | ToolContent4 | ToolContent5]
        | None
    ) = None
    id: str
    is_error: bool | None = None
    result: Any | None = None
    structured_content: Any | None = None
    type: Literal['tool.result']


class ContentPart2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image_url: ImageUrl
    type: Literal['image_url']


class ContentPart3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file: FileData
    type: Literal['file']


class ContentPart5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['video_url']
    video_url: VideoUrl


class DecisionAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: Any
    id: str | None = None
    name: str
    retry: Annotated[
        RetryOverride | None,
        Field(
            description="Layered over the agent config's policy for this kind, or over the\nengine's default for where the tool runs."
        ),
    ] = None
    type: Literal['tool.call']


class DecisionAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    content: (
        list[ToolContent1 | ToolContent2 | ToolContent3 | ToolContent4 | ToolContent5]
        | None
    ) = None
    id: str | None = None
    is_error: bool | None = None
    result: Any | None = None
    structured_content: Any | None = None
    type: Literal['tool.result']


class DecisionAction5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    code: ErrorCode | None = None
    detail: Any | None = None
    error: str
    id: str | None = None
    retryable: Annotated[bool | None, Field(description='Omitted ⇒ terminal.')] = None
    type: Literal['tool.error']


class DecisionAction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    code: ErrorCode | None = None
    detail: Any | None = None
    error: str
    id: str | None = None
    retryable: Annotated[bool | None, Field(description='Omitted ⇒ terminal.')] = None
    type: Literal['llm.error']


class DecisionAction13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: ErrorInfo
    type: Literal['fail']


class DecisionTrigger4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str
    attempt: Annotated[int, Field(ge=0)]
    deadline: AwareDatetime | None = None
    id: str
    input: Annotated[
        ToolInput1 | ToolInput2 | ToolInput3,
        Field(
            description="What the engine made of `arguments` against the tool's `input`\nschema: `valid`, `invalid`, or `malformed`. Always on the wire.",
            title='ToolInput',
        ),
    ]
    name: str
    type: Literal['tool.execute']


class DecisionTrigger5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: ErrorInfo | None = None
    id: str
    name: str
    ok: bool
    result: StoredResult | None = None
    type: Literal['tool.finished']


class DecisionTrigger6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int, Field(ge=0)]
    deadline: AwareDatetime | None = None
    format: LlmFormat | None = None
    id: str
    request: Annotated[
        Any,
        Field(
            description="The neutral `LlmRequest` JSON, or the provider's native request body\nwhen `format` is set."
        ),
    ]
    stream: bool
    type: Literal['llm.execute']


class DecisionTrigger8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    error: ErrorInfo | None = None
    id: str
    ok: bool
    result: str | None = None
    session_id: str
    type: Literal['subagent.finished']


class DecisionTrigger10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cost: Annotated[str | None, Field(pattern='^-?\\d+(\\.\\d+)?$')] = None
    data: Any | None = None
    turn_id: str
    type: Literal['turn.finished']
    usage: Usage | None = None


class DeferTools(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    max_matches: Annotated[
        int | None,
        Field(
            description='The most matches one search answers with. Never zero: a search that can\nanswer with nothing is a search the model cannot use.',
            ge=1,
        ),
    ] = None
    strategy: Annotated[
        DeferToolsStrategy | None,
        Field(description='Which tools the agent gets to reach the ones it defers.'),
    ] = None


class Effect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str | None = None
    anchor: Annotated[
        str | None, Field(description='The tree node the effect was requested at.')
    ] = None
    arguments: str | None = None
    attempt: Annotated[int, Field(ge=0)]
    deadline: AwareDatetime | None = None
    handler: Handler | None = None
    id: str
    kind: Annotated[
        EffectKind1
        | Literal['connector_sync']
        | Literal['decision']
        | Literal['turn_end'],
        Field(
            description="What kind of work an effect is. One enum for the wire and for scheduling. A\ndecision and a turn's end queue beside the calls and are swept the same way,\nso they are kinds too. Neither appears on an [`Effect`].",
            title='EffectKind',
        ),
    ]
    name: str | None = None
    session_id: Annotated[
        str | None,
        Field(
            description='The child session a subagent runs in. Its `id` is the model tool call\nthe subagent answers.'
        ),
    ] = None
    status: Annotated[EffectStatus1 | Literal['running'], Field(title='EffectStatus')]
    stream: bool | None = None


class InterruptResolution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    payload: Any | None = None
    responder: InterruptResponder | None = None
    status: ResumeStatus


class McpServer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approve: Annotated[
        Approve1 | Literal['destructive'] | None,
        Field(
            description="Which of a connection's calls stop for a person.",
            title='Approve',
        ),
    ] = None
    auth_failure: McpAuthFailure | None = None
    id: str
    tool_sync_failure: McpToolSyncFailure | None = None
    tools: Annotated[
        McpTools | None,
        Field(
            description='Narrows what the model sees. Absent ⇒ every tool the connection grants.'
        ),
    ] = None


class Reasoning(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[Any] | None = None
    provider: ReasoningProvider
    text: str | None = None


class ReasoningConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effort: ReasoningEffort | None = None
    enabled: bool | None = None
    exclude: bool | None = None
    max_tokens: Annotated[int | None, Field(ge=0)] = None


class RetryConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connector: RetryOverride | None = None
    default: RetryOverride | None = None
    llm: RetryOverride | None = None
    subagent: RetryOverride | None = None
    tool: RetryOverride | None = None


class StreamDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    finish_reason: str | None = None
    reasoning: str | None = None
    text: str | None = None
    tool_calls: list[ToolCallChunk] | None = None


class Subagent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    defer: Annotated[
        bool | None,
        Field(
            description="Keep this tool out of the request. See [`LlmTool::defer`]. Absent ⇒\nthe agent's `defer_tools`."
        ),
    ] = None
    description: str | None = None
    id: str
    mode: SubagentMode | None = None
    prefix: Annotated[
        bool | None,
        Field(description='Offer the tool as `agent__<id>` instead of `<id>`.'),
    ] = None


class SubagentTools(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    strategy: SubagentToolsStrategy | None = None
    wait: bool | None = None


class TokenDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    attempt: Annotated[int, Field(ge=0)]
    call_id: str
    finish_reason: str | None = None
    reasoning: str | None = None
    root_session_id: Annotated[str, Field(description='Transport routing key.')]
    seq: Annotated[
        int,
        Field(
            description='Per-call counter, distinct from event-store sequence.', ge=0
        ),
    ]
    session_id: Annotated[str, Field(description='May be a subagent of root.')]
    tenant_id: Annotated[
        str, Field(description='Tenant isolation key — subscribers must match.')
    ]
    text: str | None = None
    tool_calls: list[ToolCallChunk]
    turn_id: str | None = None


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    function: ToolCallFunction
    id: str
    type: str


class AgentConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attachments: Attachments | None = None
    defer_tools: Annotated[
        bool | DeferTools | None,
        Field(
            description='Defer every tool this agent offers, whatever its source. A tool or a\nconnection overrides this with its own `defer`. Absent, the agent defers\nnothing; a connection can still defer on its own.'
        ),
    ] = None
    effort: Annotated[
        ReasoningEffort | None,
        Field(
            description="How hard the model thinks. Unset leaves the provider's own default."
        ),
    ] = None
    llm: Annotated[
        str | None, Field(description="The `[llm.*]` block this agent's calls run on.")
    ] = None
    max_subagent_depth: Annotated[
        int | None,
        Field(
            description="How deep this agent's subagents may nest. A session whose depth\nreaches it may not delegate. `0` never delegates.",
            ge=0,
        ),
    ] = None
    mcp: Annotated[
        list[McpServer] | None,
        Field(description='MCP servers this agent draws tools from.'),
    ] = None
    mcp_announce: Annotated[
        McpAnnounce | None,
        Field(
            description='Whether the engine tells the model that an MCP server is available, and\nwhat that server says it is for.'
        ),
    ] = None
    model: str
    plugins: Annotated[
        list[AgentPlugin] | None, Field(description='Plugins this agent uses.')
    ] = None
    retry: Annotated[
        RetryConfig | None,
        Field(
            description='Boxed. Five per-kind overrides are too many bytes to carry inline.'
        ),
    ] = None
    subagent_tools: Annotated[
        SubagentTools | None,
        Field(
            description='What shape the subagents take as tools. Absent ⇒ one tool per agent.'
        ),
    ] = None
    subagents: Annotated[
        list[Subagent] | None,
        Field(
            description='Subagents the model can delegate to. The model sees them as tools.\nEach call starts a child session.'
        ),
    ] = None
    system: str | None = None
    tools: Annotated[
        list[AgentTool] | None,
        Field(description='Worker- or client-executed tools the model can call.'),
    ] = None


class DraftMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: (
        str
        | list[
            StoredContent1
            | StoredContent2
            | StoredContent3
            | StoredContent4
            | ContentPart1
            | ContentPart2
            | ContentPart3
            | ContentPart4
            | ContentPart5
        ]
        | None
    ) = None
    id: str | None = None
    name: str | None = None
    reasoning: Reasoning | None = None
    role: Role
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class LlmRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_completion_tokens: Annotated[int | None, Field(ge=0)] = None
    messages: list[DraftMessage]
    model: str
    reasoning: ReasoningConfig | None = None
    temperature: float | None = None
    tools: list[LlmTool] | None = None


class LlmResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str | None = None
    cost: Annotated[
        str | None,
        Field(
            description='Cost in dollars, if the provider reports it. A decimal string on the\nwire.',
            pattern='^-?\\d+(\\.\\d+)?$',
        ),
    ] = None
    finish_reason: str | None = None
    images: Annotated[
        list[ResponseImage] | None, Field(description='Images generated by the model.')
    ] = None
    model: str
    reasoning: Reasoning | None = None
    tool_calls: list[ToolCall] | None = None
    usage: Usage | None = None


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: (
        str
        | list[
            StoredContent1
            | StoredContent2
            | StoredContent3
            | StoredContent4
            | ContentPart1
            | ContentPart2
            | ContentPart3
            | ContentPart4
            | ContentPart5
        ]
        | None
    ) = None
    id: str
    name: str | None = None
    reasoning: Reasoning | None = None
    role: Role
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class Node(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Message
    parent_id: str | None = None


class MessageTree(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    head_id: str | None = None
    nodes: list[Node]


class ClientInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    message: DraftMessage
    queue: Annotated[
        bool | None,
        Field(
            description='Hold this message for the next turn instead of refusing it while a\nturn is running. Off by default.'
        ),
    ] = None
    stream: bool | None = None
    turn_id: str | None = None
    type: Literal['client.message']


class ClientInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    client: ClientContext | None = None
    messages: list[DraftMessage]
    stream: bool | None = None
    turn_id: str | None = None
    type: Literal['client.messages']


class ClientInput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    client: ClientContext | None = None
    messages: list[DraftMessage]
    queue: Annotated[
        bool | None,
        Field(
            description='Hold this batch for the next turn instead of refusing it while a\nturn is running. Off by default.'
        ),
    ] = None
    stream: bool | None = None
    turn_id: str | None = None
    type: Literal['client.append']


class ClientPayload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: DraftMessage
    stream: bool | None = None
    type: Literal['client.message']


class ClientPayload2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: ClientContext | None = None
    messages: list[DraftMessage]
    stream: bool | None = None
    type: Literal['client.messages']


class ClientPayload3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: ClientContext | None = None
    messages: list[DraftMessage]
    stream: bool | None = None
    type: Literal['client.append']


class DecisionAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str | None = None
    llm: Annotated[
        str | None,
        Field(
            description="The `[llm.*]` block this call runs on. Absent uses the config's\n`llm`. Naming another block moves this one call elsewhere."
        ),
    ] = None
    max_completion_tokens: Annotated[int | None, Field(ge=0)] = None
    messages: list[DraftMessage] | None = None
    model: str | None = None
    reasoning: ReasoningConfig | None = None
    retry: Annotated[
        RetryOverride | None,
        Field(
            description="Layered over the agent config's `llm` policy, or over the engine's\ndefault."
        ),
    ] = None
    stream: bool | None = None
    temperature: float | None = None
    tools: list[LlmTool] | None = None
    type: Literal['llm.call']


class DecisionAction7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    message: Annotated[
        DraftMessage | None,
        Field(
            description="The child's opening message. It travels with the spawn, so it\ncannot arrive before the session exists."
        ),
    ] = None
    mode: SpawnMode | None = None
    retry: Annotated[
        RetryOverride | None,
        Field(
            description="Layered over the agent config's `subagent` policy, or over the\nengine's default."
        ),
    ] = None
    session_id: str | None = None
    tool_call_id: Annotated[
        str, Field(description='The model tool call this subagent answers. Required.')
    ]
    type: Literal['subagent.spawn']


class DecisionAction8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: DraftMessage
    session_id: str
    type: Literal['message.send']


class DecisionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: (
        list[
            DecisionAction1
            | DecisionAction2
            | DecisionAction3
            | DecisionAction4
            | DecisionAction5
            | DecisionAction6
            | DecisionAction7
            | DecisionAction8
            | DecisionAction9
            | DecisionAction10
            | DecisionAction11
            | DecisionAction12
            | DecisionAction13
        ]
        | None
    ) = None
    agent: Annotated[
        AgentConfig | None,
        Field(
            description='A new agent config write; omitted keeps the current config.'
        ),
    ] = None
    channels: Annotated[
        dict[str, Any] | None,
        Field(
            description='How each channel shows this decision, keyed by channel kind. The engine\ndoes not read it.'
        ),
    ] = None
    messages: list[DraftMessage] | None = None
    state: Annotated[
        Any,
        Field(
            description='Absent or `null` keeps the current state. Send an empty value to\nclear it.'
        ),
    ] = None


class DecisionTrigger2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: Annotated[
        ClientContext,
        Field(
            description='Inputs the client declared on its run. The engine adds\n`client.tools` to the proposed config.'
        ),
    ]
    messages: list[DraftMessage]
    new_from: Annotated[int, Field(ge=0)]
    type: Literal['client.messages']


class DecisionTrigger7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cost: Annotated[str | None, Field(pattern='^-?\\d+(\\.\\d+)?$')] = None
    error: ErrorInfo | None = None
    id: str
    message: DraftMessage | None = None
    ok: bool
    refused: Annotated[
        bool | None,
        Field(
            description='True when the model declined the request. Without it, a refusal\nlooks like a turn that ended well and said nothing.'
        ),
    ] = None
    truncated: bool
    type: Literal['llm.finished']
    usage: Usage | None = None


class DecisionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent: Annotated[
        AgentConfig | None,
        Field(
            description='The agent config for the active path. `null` when none is set.'
        ),
    ] = None
    agent_id: str
    ancestry: list[str]
    attempts: Annotated[int, Field(ge=0)]
    calls: list[Effect]
    deadline: AwareDatetime | None = None
    decision_id: str
    identity: WorkerIdentity
    message_tree: MessageTree
    messages: list[Message]
    pending_calls: Annotated[
        int, Field(description='Count of in-flight `tool_call`/`subagent` calls.', ge=0)
    ]
    proposed: Annotated[
        DecisionResponse,
        Field(
            description="The engine's default continuation for `trigger`. Empty when only the\nworker can decide. Accept it by echoing it back."
        ),
    ]
    session_id: str
    state: Annotated[
        Any,
        Field(
            description='Opaque worker state: JSON the engine stores but never interprets.',
            title='WorkerState',
        ),
    ]
    trigger: Annotated[
        DecisionTrigger1
        | DecisionTrigger2
        | DecisionTrigger3
        | DecisionTrigger4
        | DecisionTrigger5
        | DecisionTrigger6
        | DecisionTrigger7
        | DecisionTrigger8
        | DecisionTrigger9
        | DecisionTrigger10,
        Field(
            description='The trigger a worker sees on the wire. There is no `ClientMessage`: the\nengine turns a bare client message into `ClientTranscript` before it sends\nit.',
            title='DecisionTrigger',
        ),
    ]
    turn_id: str | None = None
    worker: Annotated[
        WorkerRef | None,
        Field(
            description="The worker this session is pinned to. `null` when the file's own\nrouting decides."
        ),
    ] = None


class SubstructureProtocol(BaseModel):
    client_input: Annotated[
        ClientInput1
        | ClientInput2
        | ClientInput3
        | ClientInput4
        | ClientInput5
        | ClientInput6
        | ClientInput7
        | None,
        Field(
            description='Everything a client can send: submit a message, a full view, an append\nbatch, or a named action; resume an interrupt; or settle a client tool.\n\nEach variant carries only the addressing it needs. The four submit variants\ncarry `agent_id`, which routes the turn and starts the session if it is new,\nand an optional `turn_id`. A resume or settle names an interrupt or effect\nand continues whatever turn is running, so it carries neither.\n`session_id` is on the envelope.',
            title='ClientInput',
        ),
    ] = None
    client_payload: Annotated[
        ClientPayload1 | ClientPayload2 | ClientPayload3 | ClientPayload4 | None,
        Field(
            description='What a client submits: a message, its full conversation view, an append\nbatch, or a named action. The engine turns it into events and never stores\nit as it arrived.',
            title='ClientPayload',
        ),
    ] = None
    decision_request: DecisionRequest | None = None
    decision_response: DecisionResponse | None = None
    interrupt_payload: InterruptPayload | None = None
    interrupt_resolution: InterruptResolution | None = None
    stream_delta: StreamDelta | None = None
    token_delta: TokenDelta | None = None
